# Generated by Django 5.1.1 on 2024-09-30 17:37

import shop_product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(upload_to='product_category_images/', validators=[shop_product.utils.validate_image_extension]),
        ),
    ]
