# Generated by Django 5.1.1 on 2024-10-01 14:17

import shop_product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0002_alter_productcategory_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='productinformation',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[shop_product.utils.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='image',
            field=models.ImageField(upload_to='product_brand_images/', validators=[shop_product.utils.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='productimageslider',
            name='image',
            field=models.ImageField(upload_to='product_image_slider/', validators=[shop_product.utils.validate_image_extension]),
        ),
    ]
