# Generated by Django 5.1.1 on 2024-10-11 15:17

import shop_product.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_product', '0003_alter_product_managers_productinformation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_category_images/', validators=[shop_product.utils.validate_image_extension]),
        ),
    ]
